USE THUCHANH;

--1
SELECT * 
FROM NHANVIEN
WHERE TENNV LIKE 'H%' AND DTHOAI LIKE '090%5';

--2
SELECT NHANVIEN.MANV, HOLOT, TENNV, TENPB, TENCV, TDHV, HSPC
FROM NHANVIEN, PHONGBAN, LUONG, CHUCVU
WHERE NHANVIEN.MAPB = PHONGBAN.MAPB 
	AND NHANVIEN.MACV = CHUCVU.MACV 
	AND HSLUONG.MAHSL = LUONG.MAHSL
	AND NHANVIEN.MANV = LUONG.MANV
	AND PHONGBAN.TENPB LIKE N'Phòng kế toán' OR PHONGBAN.TENPB LIKE N'Phòng nhân sự'
	AND CHUCVU.HSPC >=1.5;

--3
SELECT NHANVIEN.MANV, HOLOT, TENNV, TENPB, TENCV, TDHV, HSL
FROM PHONGBAN.MAPB = NHANVIEN.MAPB 
	AND CHUCVU.MACV = NHANVIEN.MACV 
	AND NHANVIEN.MANV = LUONG.MANV
	AND HSLUONG.MAHSL = LUONG.MAHSL

