CREATE TABLE KHACHHANG(
	MAKH varchar(10),
	HOTEN nvarchar(20),
	DIACHI nvarchar(30),
	SODT varchar(12),
	PRIMARY KEY (MAKH)
	);

CREATE TABLE HOADON(
	MAHD varchar(10),
	NGAYLAP date,
	NGAYHOADON date,
	MAKH varchar(10),
	PRIMARY KEY (MAHD),
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
	);

CREATE TABLE NHACUNGCAP(
	MANCC varchar(10),
	TENNCC nvarchar(20),
	DIACHI nvarchar(30),
	SODT varchar(12),
	PRIMARY KEY (MANCC)
	);

CREATE TABLE DMHANG(
	MAHANG varchar(10),
	TENHANG nvarchar(20),
	DVT varchar(10),
	SLNHAP int,
	DGNHAP float,
	MANCC varchar(10),
	PRIMARY KEY (MAHANG),
	FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
	);

CREATE TABLE CHITIET(
	MAHD varchar(10),
	MAHANG varchar(10),
	SLBAN int,
	DGBAN float,
	FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	FOREIGN KEY (MAHANG) REFERENCES DMHANG(MAHANG)
	);

INSERT INTO KHACHHANG VALUES('KH01', N'D??ng Lê Y?n Nhi', N'?à N?ng', '0905192060');
SELECT * FROM KHACHHANG;