CREATE DATABASE QuanLyVatTu;
USE QuanLyVatTu;
CREATE TABLE PhieuXuat(
	SoPX INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NgayXuat DATE
);

CREATE TABLE ChiTietPhieuXuat(
	SoPX INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MaVTU INT,
    DGXuat FLOAT,
    SLXuat INT,
    FOREIGN KEY (SoPX) REFERENCES PhieuXuat (SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VatTu (MaVTU)
);

CREATE TABLE VatTu(
	MaVTU INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TenVTU VARCHAR(50)
);

CREATE TABLE ChiTietPhieuNhap(
    SoPN INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MaVTU INT,
    DGNhap FLOAT,
    SLNhap INT,
    FOREIGN KEY (MaVTU) REFERENCES VatTu (MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PhieuNhap (SoPN)
);
CREATE TABLE PhieuNhap(
	SoPN INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NgayNhap DATE
);

CREATE TABLE ChiTietDonDatHang(
    SoDH INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MaVTU INT,
    FOREIGN KEY (MaVTU) REFERENCES VatTu (MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DonDH (SoDH)
);
CREATE TABLE DonDH(
	SoDH INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NgayDH DATE,
    MaNCC INT,
    FOREIGN KEY (MaNCC) REFERENCES NhaCC (MaNCC)
);

CREATE TABLE NhaCC(
	MaNCC INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TenNCC VARCHAR(50),
    DiaChi VARCHAR(50)
);
CREATE TABLE SDT(
	SDT INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MaNCC INT,
    FOREIGN KEY (MaNCC) REFERENCES NhaCC (MaNCC)
);
/*
	PhieuXuat(SoPX___, NgayXuat)
    ChiTietPhieuXuat(SoPX___, MaVTU___, DGXuat, SLXuat)
    VatTu(MaVTU___, TenVTU)
    ChiTietPhieuNhap(MaVTU___, SoPN___, DGNhap, SLNhap)
    PhieuNhap(SoPN___, NgayNhap)
    ChiTietDonDatHang(MaVTU___, SoDH___)
    DonDH(SoDH___, NgayDH, MaNCC)
    NhaCC(MaNCC___, TenNCC, DiaChi)
    SDT(SDT___, MaNCC___)
*/
