CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Customer(
	cID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    cName VARCHAR(50),
    cAGE INT
);
CREATE TABLE `Order`(
	oID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    cID INT,
    oDate DATE,
    oTotalPrice FLOAT,
    FOREIGN KEY (cID) REFERENCES Customer (cID)
);

