USE LAB01;

-- 1.Tính thành tiền cho các hóa đơn: MAHD, NGAYHD, NGAYGH, SOLUONG, DONGIA, THANHTIEN?;

SELECT HOADON.MAHD, NGAYLAP, NGAYHOADON, SUM( SLBAN * DGBAN) AS THANHTIEN
FROM HOADON, CHITIET
WHERE HOADON.MAHD = CHITIET.MAHD
GROUP BY HOADON.MAHD,NGAYLAP, NGAYHOADON;

--2.Cho biết số  mặt hàng trên mỗi hóa đơn: MAHD, NGAYHD, NGAYHD, SOMATHANG?;

SELECT HOADON.MAHD, NGAYLAP, NGAYHOADON, COUNT( MAHANG) AS SOMATHANG
FROM CHITIET, HOADON
WHERE HOADON.MAHD = CHITIET.MAHD
GROUP BY HOADON.MAHD, NGAYLAP, NGAYHOADON;

--3. Tính tổng tiền cho mỗi hóa đơn: MAHD, NGAYHOADON, NGAYGH, TONGTIEN?;

SELECT HOADON.MAHD, NGAYLAP, NGAYHOADON, SUM( SLBAN * DGBAN) AS TONGTIEN
FROM CHITIET, HOADON
WHERE HOADON.MAHD = CHITIET.MAHD
GROUP BY HOADON.MAHD, NGAYLAP, NGAYHOADON, SLBAN * DGBAN;

--4. Lập ds các hóa đơn có NGAYGH trong tháng X? Thông tin tương tự câu 1;

SELECT HOADON.MAHD, NGAYLAP, NGAYHOADON, SUM( SLBAN * DGBAN) AS THANHTIEN
FROM CHITIET, HOADON
WHERE HOADON.MAHD = CHITIET.MAHD AND MONTH(NGAYHOADON) = 2
GROUP BY HOADON.MAHD, NGAYLAP, NGAYHOADON, SLBAN * DGBAN;


--5. Lập ds 3 hóa đơn có thành tiền cao nhất: thông tin tương tự câu 1;

SELECT TOP(3) HOADON.MAHD, NGAYLAP, NGAYHOADON, SUM( SLBAN * DGBAN) AS THANHTIEN
FROM CHITIET, HOADON
WHERE HOADON.MAHD = CHITIET.MAHD
GROUP BY HOADON.MAHD, NGAYLAP, NGAYHOADON, SLBAN * DGBAN;

--6. Lập ds các hóa đơn có tổng tiền >=X? MAHD, NGAYHD, NGAYHOADON, TONGTIEN 
-- và được sắp xếp tăng dần theo TONGTIEN;

SELECT HOADON.MAHD, NGAYLAP, NGAYHOADON,  SUM(SLBAN * DGBAN) AS TONGTIEN
FROM CHITIET, HOADON
WHERE HOADON.MAHD = CHITIET.MAHD
GROUP BY HOADON.MAHD, NGAYLAP, NGAYHOADON, SLBAN * DGBAN
HAVING SUM(SLBAN * DGBAN) >= 1000
ORDER BY TONGTIEN DESC;

--7. Lập ds các mặt hàng có số lượng >=10 do nhà cung cấp có mã là X1, X2 cung cấp: 
-- MANCC, TENNCC, TENHANG, SOLUONG, DONGIA, THANHTIEN;

SELECT NHACUNGCAP.MANCC, TENNCC, TENHANG, SLNHAP, SUM(SLNHAP * DGNHAP) AS THANHTIEN
FROM NHACUNGCAP, DMHANG
WHERE NHACUNGCAP.MANCC = DMHANG.MANCC AND NHACUNGCAP.MANCC LIKE 'NCC02' OR NHACUNGCAP.MANCC LIKE 'NCC01'
GROUP BY NHACUNGCAP.MANCC, TENNCC, TENHANG, SLNHAP, SLNHAP * DGNHAP
HAVING SLNHAP >= 10;

--8. Lập ds 3 nhà cung cấp có số mặt hàng cung cấp nhiều nhất: MANC, TENNCC, SOMATHANG

SELECT TOP(3) NHACUNGCAP.MANCC, TENNCC, SLNHAP
FROM NHACUNGCAP, DMHANG
WHERE NHACUNGCAP.MANCC = DMHANG.MANCC
GROUP BY NHACUNGCAP.MANCC, TENNCC, SLNHAP
ORDER BY SLNHAP DESC;

--9. Lập ds các hóa đơn có ngày đặt hàng trước X ngày? MAHD, NGAYHD, NGAYGH, SOLUONG, DONGIA, THANHTIEN
-- và được sắp xếp giảm dần theo THANHTIEN;

SELECT HOADON.MAHD, NGAYLAP, NGAYHOADON, SLBAN, DGBAN, SUM( SLBAN * DGBAN) AS THANHTIEN
FROM HOADON, CHITIET
WHERE HOADON.MAHD = CHITIET.MAHD AND 
GROUP BY HOADON.MAHD, NGAYLAP, NGAYHOADON, SLBAN, DGBAN, SLBAN * DGBAN;


